# Production Environment Configuration for Cloud Run
# This file defines environment variables that reference Google Cloud Secret Manager secrets

# Database Configuration
DATABASE_URL:
  secretKeyRef:
    name: database-url
    version: latest

DATABASE_SSL_MODE: require

# AI Provider Configuration
OPENAI_API_KEY:
  secretKeyRef:
    name: openai-api-key
    version: latest

GEMINI_API_KEY:
  secretKeyRef:
    name: gemini-api-key
    version: latest

CLAUDE_API_KEY:
  secretKeyRef:
    name: claude-api-key
    version: latest

QWEN_API_KEY:
  secretKeyRef:
    name: qwen-api-key
    version: latest

OPENROUTER_API_KEY:
  secretKeyRef:
    name: openrouter-api-key
    version: latest

# Email Service Configuration
SENDGRID_API_KEY:
  secretKeyRef:
    name: sendgrid-api-key
    version: latest

SMTP_HOST: smtp.sendgrid.net
SMTP_PORT: 587
SMTP_USERNAME:
  secretKeyRef:
    name: smtp-username
    version: latest

SMTP_PASSWORD:
  secretKeyRef:
    name: smtp-password
    version: latest

# Payment Processor Configuration
STRIPE_SECRET_KEY:
  secretKeyRef:
    name: stripe-secret-key
    version: latest

STRIPE_WEBHOOK_SECRET:
  secretKeyRef:
    name: stripe-webhook-secret
    version: latest

PAYPAL_CLIENT_ID: # Set via Cloud Console or deployment script
PAYPAL_CLIENT_SECRET:
  secretKeyRef:
    name: paypal-client-secret
    version: latest

# Application Security
JWT_SECRET:
  secretKeyRef:
    name: jwt-secret
    version: latest

SESSION_SECRET:
  secretKeyRef:
    name: session-secret
    version: latest

API_ENCRYPTION_KEY:
  secretKeyRef:
    name: api-encryption-key
    version: latest

# Firebase Configuration
FIREBASE_ADMIN_KEY:
  secretKeyRef:
    name: firebase-admin-key
    version: latest

FIREBASE_CONFIG:
  secretKeyRef:
    name: firebase-config
    version: latest

# External Services
GITINGEST_API_KEY:
  secretKeyRef:
    name: gitingest-api-key
    version: latest

WEBHOOK_SIGNING_SECRET:
  secretKeyRef:
    name: webhook-signing-secret
    version: latest

# Application Configuration
NODE_ENV: production
NEXT_PUBLIC_APP_URL: https://baseline-analyzer.web.app
NEXT_PUBLIC_API_URL: https://api-baseline-analyzer-[hash]-uc.a.run.app

# Google Cloud Configuration
GOOGLE_CLOUD_PROJECT: # Set via deployment
GOOGLE_CLOUD_REGION: us-central1

# Logging and Monitoring
LOG_LEVEL: info
ENABLE_CLOUD_LOGGING: true
ENABLE_CLOUD_MONITORING: true

# Performance Configuration
MAX_CONCURRENT_ANALYSES: 10
ANALYSIS_TIMEOUT_MS: 300000
DATABASE_POOL_SIZE: 20
REDIS_CACHE_TTL: 3600

# Security Configuration
CORS_ORIGINS: https://baseline-analyzer.web.app,https://baseline-analyzer.firebaseapp.com
RATE_LIMIT_WINDOW_MS: 900000
RATE_LIMIT_MAX_REQUESTS: 100
ENABLE_AUDIT_LOGGING: true