name: Simple Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  simple-test:
    name: Simple Test Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Echo test
        run: echo "Hello from GitHub Actions!"
        
      - name: List files
        run: ls -la